### ISSUE TITLE
Question: can I use more than one forge?

### ISSUE THREAD

**Issue by JCotton1123** [maestrodev/librarian-puppet#12]
All of the example config files I've seen include a single "forge" declaration at the top of the Puppetfile. I want to use more than one forge. Looking at the source it appears I should be able to do the following however it throws an error. Any ideas?

```
mod "puppetlabs/ntp",
  :forge => "http://forge.puppetlabs.com"
```

which throws

```
/usr/lib/ruby/gems/1.8/gems/librarian-0.1.1/lib/librarian/dependency.rb:113:in `cache_manifests!': undefined method `manifests' for []:Array (NoMethodError)
```

OR 

```
mod "puppetlabs/ntp",
  :source => "http://forge.puppetlabs.com" 
```

which throws 

```
Could not resolve the dependencies.
```

**Comment by carlossg** [comment]
I never considered that, probably the caching of the forge data has broken the :forge parameter
