### ISSUE TITLE
Submit upstream?

### ISSUE THREAD

**Issue by patcon** [maestrodev/librarian-puppet#4]
Hey! Not to get on your case or anything, but any reason why you guys aren't interested in submitting your patches upstream to @rodjek's repo? I'm just seeing that it's causing a bit of fragmentation as others are starting to use your gem/project too, so I was curious :)

**Comment by brettporter** [comment]
I believe we have pull requests open for all of the patches already. We're certainly open to any suggestions on how to make them easier to integrate upstream!

**Comment by patcon** [comment]
Thanks brett! Sorry, I tried searching with github's advanced search, but I guess still figuring it out.. :/

**Comment by adamcstephens** [comment]
Has anyone approached @rodjek about creating a shared project?

**Comment by rodjek** [comment]
So, many of the open pull requests were merged in for the 0.9.8 release a few weeks ago.  I'm hoping to have a decent block of time in the next couple of weeks to spend getting librarian-puppet up to date with respect to issues & pull requests.

**Comment by patcon** [comment]
Hm. Good point. Anyone mind if I open an issue in his queues about having a co-maintainer? I'm not thinking myself as I'm mainly into Chef, not Puppet, so I thought I'd double-check that it's ok with y'all

cc: @zifik

**Comment by zifik** [comment]
We have plans to use it in the workplace and I've already made contributions to get it working behind a proxy. I'm game for helping out, but I'm still new to ruby. 

As for the fragmentation, I'll gladly shut down my fork as soon as the features I really need are merged.

**Comment by carlossg** [comment]
I opened an full pull request at https://github.com/rodjek/librarian-puppet/pull/73
