### ISSUE TITLE
Versions are not read properly for git modules

### ISSUE THREAD

**Issue by inkblot** [maestrodev/librarian-puppet#5]
I think I have found a case that illustrates the behavior that I am seeing.  Specifically, when a Puppetfile sources a module from a git repo, librarian-puppet seems to ignore the version declared in the module's Modulefile.

I have put together a simple test case for this at https://github.com/inkblot/break-librarian-puppet.  In this test case, I am trying to fetch a fork of puppetlabs/apache and a fork of puppetlabs/passenger.  The passenger module requires apache >= 0.0.3, which should be satisfied by the apache module as specified in the Puppetfile, which is version 0.6.0.  The librarian-puppet output is at https://gist.github.com/inkblot/5401854.

**Comment by carlossg** [comment]
Applied pull request #6

**Comment by inkblot** [comment]
Ultimately, it appears that the issue was specifically with reading the version from the puppetlabs-apache module, since placing any constraint on its version caused the return value of Git::Repository#fetch_version to be ''.  Thanks for the quick release!
