### ISSUE TITLE
ignore dependencies

### ISSUE THREAD

**Issue by bodepd** [maestrodev/librarian-puppet#7]
Hi,

Just curious if you would accept a patch for something before I go through the trouble of writing it.

I would really like to have an option for librarian-puppet that ignores all attempts at dependency resolution (and does not even bother looking inside of the Modulefiles).

I often run into a myriad of issues related to invalid modulefiles, dependency mismatches etc, and I am quite comfortable ensuring that I specify all of my required repos along with their desired versions.

**Comment by carlossg** [comment]
It makes sense. How do you envision someone specifying that on the puppetfile or command line?
It'd be good to check if librarian or librarian-chef have something already implemented

**Comment by bodepd** [comment]
I tried to implement it as --ignore-deps

```
resolve! unless options["ignore-deps"]
```

but it looks like resolve does a lot more than just resolve deps.

**Comment by bodepd** [comment]
I had a peek at the librarian code and didn't really see anything that looked like it might support this. The code that does the actual downloads is also really tangled up with the code that does the dependency resolution.
